Stripe Payments Scripts and Test
Syncano/syncano-socket-stripe-payments pull request #1
Opened 2018-01-02 06:26 UTC by Andela-callen

#### What does this PR do?
Allows users to process stripe payments actions

#### Description of Task to be completed?
 -  As a developer, I want to be able to call actions such as balance, bank accounts, cards, etc using stripe payment service so that data gotten can be useful

#### What are the relevant JIRA stories?
`SL-32`

2018-01-02 14:10 UTC, adamwardecki requested changes
Ok, looks goods in general. Please fix the following things:
- Refactor the function checking the request method  into a utility function that will also handle the error throwing
- use template literals for multiline strings
- Use `GET` http method for list endpoints

2018-01-02 14:10 UTC, adamwardecki commented on package.json
> +    "babel-cli": "^6.26.0",
Is this package necessary?

2018-01-02 14:10 UTC, adamwardecki commented on socket.yml
> +description: Stripe offers payment solutions for businesses.
Bit more verbose description: link to stripe website, what endpoints the socket covers, link to stripe docs etc.

2018-01-02 14:10 UTC, adamwardecki commented on socket.yml
> +      chargeID:
Add info that this param is required for retrieve, update and shouldn't be passed for create

2018-01-02 14:10 UTC, adamwardecki commented on socket.yml
> +    description: Create, Retrieve, Update and Delete  actions for customer.
Double space between "Delete" and "actions"

2018-01-02 14:10 UTC, adamwardecki commented on socket.yml
> +          Reference Stripe API reference documentation.
"Reference Stripe API reference documentation." this could be phrased better

2018-01-02 14:10 UTC, adamwardecki commented on socket.yml
> +    description: Create, Retrieve, Update and Delete  actions for bank account.
double space

2018-01-02 14:10 UTC, adamwardecki commented on socket.yml
> +    description: Returns  a list of the bank accounts belonging to a Customer.
double space

2018-01-02 14:10 UTC, adamwardecki commented on socket.yml
> +    description: Create, Retrieve, Update and Delete  actions for cards.
double space

2018-01-02 14:10 UTC, adamwardecki commented on src/balance/listAllBalance.js
> +  const log = logger('Socket scope');
Remove the log if not used

2018-01-02 14:10 UTC, adamwardecki commented on src/balance/listAllBalance.js
> +    if (ctx.meta.request.REQUEST_METHOD === 'POST') {
Should be `GET` method

2018-01-02 14:10 UTC, adamwardecki commented on src/balance/retrieveBalance.js
> +  const log = logger('Socket scope');
remove if not used

2018-01-02 14:10 UTC, adamwardecki commented on src/balance/retrieveBalanceTransaction.js
> +  const log = logger('Socket scope');
same as above and concerns all the script files

2018-01-02 14:10 UTC, adamwardecki commented on src/bankAccounts/bankAccount.js
> +      'Make sure to use `POST`, `GET`, `PUT` & `DELETE` request method for creating, ' +
use template literals for multiline strings

2018-01-02 14:10 UTC, adamwardecki commented on src/bankAccounts/bankAccount.js
> +      const updateBankAccount = await stripe.customers.updateCard(
Looks like a bug in Stripe docs. It should be `updateSource`. Confirm and let me know

2018-01-02 14:10 UTC, adamwardecki commented on src/bankAccounts/listAllBankAccts.js
> +    if (requestMethod === 'POST') {
should be  `GET` request type for list methods

2018-01-02 14:10 UTC, adamwardecki commented on src/balance/retrieveBalance.js
> +    if (ctx.meta.request.REQUEST_METHOD === 'GET') {
The request type check is made in multiple scripts. Abstract it into a utility function (along with the throw error statement) and move before the try catch blocks in all the scrtips.

2018-01-02 14:10 UTC, adamwardecki commented on src/balance/retrieveBalanceTransaction.js
> +  } catch (err) {
catch ({ type, message, statusCode }) { response.json({ type, message, statusCode })}

2018-01-02 14:10 UTC, adamwardecki commented on src/cards/listAllCards.js
> +    if (requestMethod === 'POST') {
`GET` for listing

2018-01-02 14:10 UTC, adamwardecki commented on src/charge/listAllCharges.js
> +    if (ctx.meta.request.REQUEST_METHOD === 'POST') {
`GET`

2018-01-02 14:10 UTC, adamwardecki commented on src/customers/customer.js
> +      const deleteStripeCustomer = await stripe.customers.update(customerID);
Nope. Should be `stripe.customers.del()`.

2018-01-02 14:10 UTC, adamwardecki commented on src/customers/listAllCustomers.js
> +    if (ctx.meta.request.REQUEST_METHOD === 'POST') {
`GET`

2018-01-02 14:10 UTC, adamwardecki commented on src/disputes/listAllDisputes.js
> +    if (ctx.meta.request.REQUEST_METHOD === 'POST') {
`GET`

2018-01-02 14:10 UTC, adamwardecki commented on test/balanceTest.js
> +        + 'method for retrieving balance.');
template literals

2018-01-02 14:10 UTC, adamwardecki commented on test/chargeTest.js
> +// const source = '';
remove unnecessary comments

2018-01-04 05:47 UTC, Andela-callen commented on package.json
> +    "babel-cli": "^6.26.0",
Fixed

2018-01-04 05:50 UTC, Andela-callen commented on socket.yml
> +    description: Create, Retrieve, Update and Delete  actions for customer.
fixed

2018-01-04 05:50 UTC, Andela-callen commented on socket.yml
> +    description: Create, Retrieve, Update and Delete  actions for bank account.
fixed

2018-01-04 05:51 UTC, Andela-callen commented on socket.yml
> +    description: Returns  a list of the bank accounts belonging to a Customer.
fixed

2018-01-04 05:51 UTC, Andela-callen commented on socket.yml
> +    description: Create, Retrieve, Update and Delete  actions for cards.
fixed

2018-01-04 05:51 UTC, Andela-callen commented on src/balance/listAllBalance.js
> +  const log = logger('Socket scope');
fixed

2018-01-04 06:25 UTC, Andela-callen commented on src/balance/retrieveBalance.js
> +  const log = logger('Socket scope');
fixed

2018-01-04 06:56 UTC, Andela-callen commented on src/balance/retrieveBalanceTransaction.js
> +  const log = logger('Socket scope');
fixed

2018-01-09 14:41 UTC, Andela-callen commented on src/balance/retrieveBalanceTransaction.js
> +  } catch (err) {
fixed

2018-01-09 14:43 UTC, Andela-callen commented on src/bankAccounts/bankAccount.js
> +      const updateBankAccount = await stripe.customers.updateCard(
it actually shows `updateCard`

2018-01-10 09:22 UTC, adamwardecki commented on src/bankAccounts/bankAccount.js
> +      const updateBankAccount = await stripe.customers.updateCard(
@Andela-callen You mean it shows `updateCard` in the stripe docs? I know, but it seems to me it's a bug in their documentation.

2018-01-15 07:05 UTC, Andela-callen commented on socket.yml
> +      chargeID:
fixed

2018-01-15 07:19 UTC, Andela-callen commented on socket.yml
> +description: Stripe offers payment solutions for businesses.
fixed

2018-01-15 07:31 UTC, Andela-callen commented on socket.yml
> +          Reference Stripe API reference documentation.
fixed

2018-01-15 08:15 UTC, Andela-callen commented on src/bankAccounts/bankAccount.js
> +      const updateBankAccount = await stripe.customers.updateCard(
yes, I think it is a bug too, because this `stripe.customers.updateSource` works perfectly.

2018-01-15 14:38 UTC, adamwardecki commented
The point of creating the `checkRequestType` helper method was that you wouldn't have to use the `if` clause on the endpoints where there's only one request type used.

Also, it would be better to do `if (methodType === 'PUT')` instead of `if (methodType === requestedMethodTypes[x])` because the latter adds unnecessary abstraction. 

Let's leave this as it is though and get back to it when doing a readme for this socket

2018-01-15 14:38 UTC, adamwardecki approved these changes

2018-01-16 14:21 UTC, merged